### ISSUE TITLE
Something wrong with this.

### ISSUE THREAD

**Issue by hantu152** [25huizengek1/ViTune#466]
### Steps to reproduce the bug

when i tried to play the song, it just came up like this. and shows a text at the top of the cover albums says "The returned video ID doesn't match the requested one"

### Expected behavior

i expected to be played.

### Actual behavior

and then that things show up

### Screenshots/Screen recordings

![Screenshot_20241012-114413](https://github.com/user-attachments/assets/48c5980e-ca4b-4966-9169-4620bd143c99)

### ViTune version

1.0.9

### What kind of build are you using
Release 

GitHub

### Android version

Android 10

### Device info

I'm Using Infinix Hot 10 Android 10

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Fixed in the latest release.

**Comment by brnwlshubh** [comment]
@25huizengek1 I'm using the latest beta version.
I'm still facing this issue.
