### ISSUE TITLE
Viper not working with vitune

### ISSUE THREAD

**Issue by ojaghiradin** [25huizengek1/ViTune#562]
### Steps to reproduce the bug

Enable viper and play any song from vitune

### Expected behavior

Viper FX should take effect

### Actual behavior

Viper doesn't recognise vitune even in legacy mode. 
( Works with any other media player )

### ViTune version

V1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Device : Poco X3 pro ( vayu )
Rom / OS : Skyline UI , A14
Root method : Magisk 28

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
Omagad Poko 🐡💥

**Comment by 25huizengek1** [comment]
Should be fixed by ae73773013e0b7aa457e5371f6c65b382ffe56cd

I cannot test this though. I won't root my device for this.

**Comment by ojaghiradin** [comment]
Thank you so much for fixing it
Although, it still doesn't work without legacy mode enabled 

But, again, thank you so much for putting the effort and fixing it ❤️
